### ISSUE TITLE
Bounding boxes which are out of image when augmentation applied

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [emadboctorx/yolo-tf2#20]
Hi, you are using imgaug library to augment the dataset. When i use geometric operation like rotation, translation etc.., resulted bounding boxes might go out of image region, I could notice that this case is not being handled in this implementation. Did i miss anything?

**Comment by emadboctorx** [comment]
That is an issue I'm aware of and I think i included that in the docs / README i'm not sure but don not use geometric augmentation that involves 45 rotations  because this for some reason results in what you're indicating. There are a bunch of other augmentations you can try which are safe and will work fine.

**Comment by VeeranjaneyuluToka** [comment]
I have fixed this issue in my own codebase taken from your github, basically you need to get rid off from the bounding boxes which are out of image region, for that you need to add augmented_boxes = augmented_boxes.remove_out_of_image().clip_out_of_image() after you apply augmentation operation and consider this modification in update_data  function in augmentor.py. Thanks for replying back to me.

**Comment by emadboctorx** [comment]
Thanks, let me know if you face any other issues.
