### ISSUE TITLE
Use on Multi-channel data

### ISSUE THREAD

**Issue by jlovick** [emadboctorx/yolo-tf2#8]
Thank you very much for this great repo! I am learning a lot from reading your code
i am working with remote sensing (satellite)  imagery with many data channels in addition to RGB, can you comment on its use with multichannel (4+ ) image data, do you believe many code changes would be required to get it to work with such data?
Thanks!

**Comment by emadboctorx** [comment]
You're welcome :) I never came across your problem since I never needed to use multichannel images however I'll take a wild guess here: try setting the input shape to (416, 416, n) with n being the number of channels, if any problems encountered, then figure out a way to convert your images to RGB and use the converted images instead of modifying the code
